### ISSUE TITLE
UseContainer no longer available

### ISSUE THREAD

**Issue by jakenuts** [loresoft/KickStart#8]
Not sure how to update this code given the refactoring:

` Kick.Start(config => config
                        .IncludeLoadedAssemblies()
                        .UseAutofac(a => a.Container(c => RootContainer = c))
                        .UseStartupTask(c => c.UseContainer())
                    );`

Any ideas? 

Thanks so much!

**Comment by pwelter34** [comment]
the container will be used by default now.  If no container was set or couldn't resolve, falls back to Activator.CreateInstance.  

See https://github.com/loresoft/KickStart/blob/master/src/KickStart/Context.cs#L119

**Comment by jakenuts** [comment]
Perfect, that makes sense. Thanks! 8)

**Comment by jakenuts** [comment]
I'm getting "no parameterless contstructor" errors and it appears that Activator.CreateInstance is still being used despite setting up Autofac. It seems possibly related to the fact that the ServiceProvider in Kick is set at the end of the Start() method after the starters have run?

**Comment by pwelter34** [comment]
our you using Kick.ServiceProvider some where in the startup process?  you'll have to change to inject the things you'll need or inject the container.

**Comment by jakenuts** [comment]
Sorry for the delay. It seems like the startup tasks are "Run()" before the service provider is assigned (the last line of the Start() method. I guess UseContainer used to assign that before the StartupTasks were constructed which allowed Autofac to do that work.

**Comment by pwelter34** [comment]
the order you call the Use() methods matter, it runs them in the order called.  So if you have UserStartupTasks before UserAutofac, then use, the startup tasks would run before the container is setup.  Hope that helps.

**Comment by jakenuts** [comment]
So sorry, it turned out to be that I was registering startup tasks as their interfaces (.As<IStartupTask>()) rather than their concrete types (.AsSelf()). Thanks so much for keeping up with this. 8)
