### ISSUE TITLE
What happened to Kick.Container and how can I access it now?

### ISSUE THREAD

**Issue by brbradford** [loresoft/KickStart#9]
We use Kick.Container in several places in our code but after upgrading to your latest version it is gone. What is the recommended way to access the container now? (We don't want to switch to using ServiceProvider because we have quite a bit of code that references the Unity container). Thanks.

**Comment by pwelter34** [comment]
It was renamed to Kick.ServiceProvider.  See change log.

https://github.com/loresoft/KickStart#version-40
